### ISSUE TITLE
Application hangs, no output

### ISSUE THREAD

**Issue by interceptor** [sphereio/csv-mapper#2]
Hello, I have been trying to get csv-mapper to run, I am using node 0.12.2. using  the following command:

csv-mapper -m test-data/test-mapping.json --inCsv test-data/test-small.csv

The program does not quit, no erros. it just sits there, no output to stdout.

Any clues what I am doing wrong?

Thank you for pointing me in the right direction.

**Comment by OlegIlyenko** [comment]
Thanks for sharing this! I think I used node 0.11, so maybe the problem is with the version of it. I will check it tomorrow. Are you using the `test-mapping.json` and `test-small.csv` from the project itself, of have changed them in some way?

**Comment by interceptor** [comment]
Oh am glad that you reply, was worried that this project was already abandoned :) I have not modified the test files, they are vanilla from within your project.
I shall have a go with node 0.11, and see if it helps.

**Comment by interceptor** [comment]
ok, tried tested it like this (same result, just hangs):

nvm run 0.11.16 ~/node_modules/csv-mapper/bin/csv-mapper.js -m test-data/test-mapping.json --inCsv test-data/test-small.csv

Output is:

Running node v0.11.16

**Comment by OlegIlyenko** [comment]
I think I have an idea. If application can't find provided `inCsv` file, it will fall back to stdin. This will give an impression that it hangs, but in reality it just expects user input. To verify it, you can check that the file is really accessible and readable from the current working directory where you start the application. Also if it "hangs", try to type several lines and then press `CTRL + D` (EOF) this should produce some output and exit.

**Comment by interceptor** [comment]
Thanks for the tip, I will give it a shot tonight, perhaps I am just silly :P

**Comment by interceptor** [comment]
Good evening, this is what I tried, and unfortunetely didnt work yet:

nvm run 0.11.16 /home/mike/node_modules/csv-mapper/bin/csv-mapper.js -m /home/mike/node_modules/csv-mapper/test-mapping.json --inCsv  /home/mike/node_modules/csv-mapper/test-small.csv

Note I have used fully qualified paths now (no "~") and also copied the test files directly with the csv-mapper dir.... I do get the following output though:

Error: ENOENT, open 'test-data/test-lookup.csv at Error (native)'

This is surprising, note that it is looking for a test file that I did not mention in my call...

**Comment by interceptor** [comment]
ok, I found out that the test-mapping.json is referencing the test-lookup.csv.... thats unexpected!

**Comment by OlegIlyenko** [comment]
yeah, exactly. So indeed, the problems is that it could not find the `test-data/test-mapping.json` so it falls back to `stdin`. Lookup value transformer allows to specify lookup values in file or URL. in case of the file it will try to find it relatively to the current working directory, where you started the application. 

But I think I will change the behavior in case `--inCsv` is not found. Instead falling back to `stdin` it's probably better to report an error and exit.

BTW, have this helped - can you see the output now?

**Comment by interceptor** [comment]
Not really, I seem to fail to satisfy the --inCSV parameter... I dont know why.

**Comment by OlegIlyenko** [comment]
ok, maybe you can try this:

```
git clone https://github.com/sphereio/csv-mapper.git
cd csv-mapper
csv-mapper -m test-data/test-mapping.json --inCsv test-data/test-small.csv
```

just to make sure that all paths are correct and all files are there.

**Comment by OlegIlyenko** [comment]
BTW, I just released version 1.0.8 which reports an error if provided `--inCsv` file does not exist.

**Comment by interceptor** [comment]
I did build from your git source repo, will try again with 1.0.8 :)

**Comment by emmenko** [comment]
I will add two things:
- don't use node 0.11 (it's the unstable version), always use even versions (0.10, 0.12...). Also specify those version you want to test in travis.yml
- regarding the stdin thingy, I will make it explicit via a command option (so if you provide that it will listen for inputs). Still, good to report an error for inCsv

**Comment by interceptor** [comment]
Helloo again,

I did pull latest git version, and successfully ran your example with node 0.12:

git clone https://github.com/sphereio/csv-mapper.git
cd csv-mapper
csv-mapper -m test-data/test-mapping.json --inCsv test-data/test-small.csv

I will now start malking my own mapping, I need to convert a CSV export to match a Prestashop CSV template format, so I can import Shop Data :+1:

**Comment by OlegIlyenko** [comment]
:+1: nice! Glad that it works for you now
