### ISSUE TITLE
Poor error message if mapping file is not valid JSON

### ISSUE THREAD

**Issue by ifross89** [sphereio/csv-mapper#3]
I had an unterminated array in my mapping file.

When I used this as my mapping file, the program (obviously) did not run successfully, but instead of a useful error message, all that was output was `undefined`.

A useful error message should be generated if the JSON parsing fails.

**Comment by OlegIlyenko** [comment]
Thanks for pointing this out. It was was introduced as i switched to YAML parser, which uses different error type. Just released the fix in version **1.0.8**.
