### ISSUE TITLE
ValueTransformers type regex replaces if no match is found

### ISSUE THREAD

**Issue by interceptor** [sphereio/csv-mapper#4]
Hello again :)

I have been busy trying to get the mappings working that I need, an I think I have come across the following Problem:

I am trying to Replace a Value depending on its content:

```
            "valueTransformers": [
                {"type": "print"},
                {"type": "regexp", "find": "^(Books)$", "replace": "55"},
                {"type": "print"},
                {"type": "regexp", "find": "^(Figurines)$", "replace": "54"},
            ]
```

What happends is, that if the Value "Books" is not found, "undefined" is passed on to the next value transformer... This makes If/else logic implementation impossible.

Also, even if only one regex value transformer is defined, it appears that if no match is found, the value "undefined" is passed on and you end up with no value (empty string) being written into your target CSV.

Do I abuse your concept here, or do I missunderstand something?

Greetings,
Mike

**Comment by OlegIlyenko** [comment]
No, you are not misusing it. Regex transformer is pretty strict in this sense. So you can always detect, that regexp was not matched (in most of the use-cases I faced before, regexps were expected to match - if they do not match then the data was wrong and either an empty value or an error was more desired than original unmodified value). 

There is also 2 value transformers that help to deal with undefined values. `required` VT will result in error for undefined values - you can use it if empty values are not allowed to be present in the output and you want to make sure that regexp always matches (`required` should be the last value transformer in the chain).

You can also use `fallback` VT if you want to do something different in case value is not defined. `fallback` tries different alternative VT one by one and returns first non-undefined value.

Most of other built-in VT are just ignoring undefined values, so undefined values generally do not produce error, but instead result in empty output values.

**Comment by interceptor** [comment]
Hi Oleg,

thank you for your quick response and clarification :) This is what I came up with:

```
{
    "type": "addColumn",
    "toCol": "Tax rules ID",
    "valueTransformers": [{
        {"Adding Column for Prestashop Tax Rules - ID 55 for CH Super Reduced Rate (2.5%), ID 54 for CH Reduced Rate (3.8%), ID 53 for CH Standard Rate (8.0%)"},
        "type": "multipartString",
        "parts": [{
            "fromCol": "Family",
            "valueTransformers": [{
                "type": "fallback",
                {"type": "regexp", "find": "^(Livres)$", "replace": "55"},
                {"type": "regexp", "find": "^(Figurines)$", "replace": "54"},
                {"type": "regexp", "find": "^(DVD)$", "replace": "53"},
                {"type": "required"}
            }]
        }]
  }]
```

Unfortunately it does'nt do yet what I would like; this currently does not replace the values with the numbers, but the target CSV simply ends up with the strings "Livres", "Figurines" or "DVD"... what am I overlooking?

Greetings,
Mike

**Comment by interceptor** [comment]
Hi Oleg,

I just can't make any progress, I sank 12+ hours into this I just cant make enough sense of the syntax and what can be nested how etc...

The following successfully writed "55" in the the target CSV  "Tax rules ID" column:

```
{
    "type": "transformColumn",
    "toCol": "Tax rules ID",
    "fromCol": "Family",
    "valueTransformers": [
        {"type": "print"},
        {"type": "regexp", "find": "^(Livres)$", "replace": "55"},
    ]
}
```

From my previous attempt above, you should see what I am trying to do... I need to get the other values "54" and "53" written in case of "Figures" and "DVD" respectively.

Can you give me a hand? I don't know what I should do anymore - I soon have to give up .

**Comment by OlegIlyenko** [comment]
no worries, just give me a sec and we will figure it out :)

**Comment by OlegIlyenko** [comment]
Ok, the problem with your original solution was that `fallback` is also needs a list of `valueTransformers`. So the correct way to write it would be:

```
{
  description: "Test mapping",

  columnMapping: [{
    type: "addColumn",
    toCol: "Tax rules ID",

    valueTransformers: [{
      # Adding Column for Prestashop Tax Rules - ID 55 for CH Super Reduced Rate (2.5%), ID 54 for CH Reduced Rate (3.8%), ID 53 for CH Standard Rate (8.0%)
      type: "multipartString",

      parts: [{
        fromCol: "Family",

        valueTransformers: [{
          type: "fallback",
          valueTransformers: [
            {type: "regexp", find: "^(Livres)$", replace: "55"},
            {type: "regexp", find: "^(Figurines)$", replace: "54"},
            {type: "regexp", find: "^(DVD)$", replace: "53"}
          ]
        }]
      }]
    }]
  }]
}
```

The thing is that the mapping parser is actually a YAML parser, so it allows a little bit relaxed syntax, which can makes it easy to write invalid json structure (like in your case list of json objects with value transformers was not nested in the json list, but was defined directly in the body of another object). From the other hand, it allows to YAML  syntax for mappings and also nice things comments (with `#`)

I also wanted to point out, that for your use-case you can use `lookup` value transformer. it was designed for this kind of value transformations. Here is an example how you can use it:

```
{
  description: "Test mapping",

  columnMapping: [{
    type: "addColumn",
    toCol: "Tax rules ID",

    valueTransformers: [{
      # Adding Column for Prestashop Tax Rules - ID 55 for CH Super Reduced Rate (2.5%), ID 54 for CH Reduced Rate (3.8%), ID 53 for CH Standard Rate (8.0%)
      type: "multipartString",

      parts: [{
        fromCol: "Family",

        valueTransformers: [
          {type: "lookup", header: true, keyCol: "Value", valueCol: "ID", "values": [
            ["Value",     "ID"],
            ["Livres",    "55"],
            ["Figurines", "54"],
            ["DVD",       "53"]
          ]},
          {type: "required"}
        ]
      }]
    }]
  }]
}
```

Nice thing about `lookup` is that it can load lookup table from local file or any URL. So you don't need hard-code these codes in the mapping itself.

Hope this helps. If you have any further issues/questions, please feel free to ask :)

**Comment by interceptor** [comment]
Woa, thank you for your efforts!

I understand that the above syntax is "YAML" - to my surprise I "mixed" it in with my existing JSON-Compliant code in the mapping file... and it works!? Talking about lenient :P

I also replaced {type: "reject"} -> {type: "required"} ;)

**Comment by OlegIlyenko** [comment]
Nice, glad that it worked! yeah, this `"reject"` was a mistake, it should be `"required"` :)

**Comment by interceptor** [comment]
I think this Issue can now ben resolved/closed. Thank you!
